version: '3'
services:
  temperature_app:
    build: .                        
    ports:
      - "5001:5001"                 
      - "8001:8001"                  
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=5001
      - METRICS_PORT=8001
    image: temperature_app
    container_name: temperature_app
    depends_on:
      - prometheus                   
      - grafana                      
    networks:
      - monitoring
    volumes:
      - ./app:/app                  
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.prod.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9091"                 
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3001"                  
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
