pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'temperature_app'
        REPO_URL = 'https://github.com/OksanaBabychevska/panda-py'
        CONTAINER_NAME = 'temperature_app' 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'main']], 
                    userRemoteConfigs: [[url: REPO_URL]])
            }
        }
        stage('Stop Existing Containers') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'docker-compose down --volumes --remove-orphans'  // Linux command
                        sh 'docker rmi $(docker images -q) || true'
                    } else {
                        bat 'docker-compose down --volumes --remove-orphans'  // Windows command
                        bat '''
                for /f "tokens=*" %%i in ('docker images -q') do docker rmi %%i
                '''  
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    // List the contents of the workspace (for debugging)
                    if (isUnix()) {
                        sh 'ls -l'  // Linux command
                    } else {
                        bat 'dir'  // Windows command
                    }

                    // Build the Docker image with the tag 'temperature_app'
                    if (isUnix()) {
                        sh "docker build -t ${DOCKER_IMAGE} ."  // Linux command
                    } else {
                        bat "docker build -t ${DOCKER_IMAGE} ."  // Windows command
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        if (isUnix()) {
                               sh 'docker-compose up -d'
                               sh 'docker-compose ps -a'
                               sh 'docker logs temperature_app'
                               sh "docker exec ${DOCKER_IMAGE} python /app/tests/test_app.py"
                               sh 'docker-compose down'
                            } else {
                                bat 'docker-compose up -d'
                                bat 'docker-compose ps -a'
                                bat 'docker logs temperature_app'
                                bat "docker exec ${DOCKER_IMAGE} python /app/tests/test_app.py"
                                sh 'docker-compose down'
                        } 
                            }
                    }
                }
            }

        stage('Deploy to Production') {
            when {
                expression { return currentBuild.result == 'SUCCESS' }
            }
            steps {
                script {
                    // Deploy to production using the production docker-compose file
                    if (isUnix()) {
                        sh 'docker-compose up -d'  // Linux command
                    } else {
                        bat 'docker-compose up -d'  // Windows command
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean the workspace after each build
            cleanWs()
        }
    }
}
