pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'temperature_app'
        REPO_URL = 'https://github.com/OksanaBabychevska/panda-py'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: 'main']], 
                    userRemoteConfigs: [[url: REPO_URL]])
            }
        }

        stage('Build') {
            steps {
                script {
                    sh docker build -t [[DOCKER_IMAGE]] .
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {

                        sh docker-compose up -d
                        
                        def containerId = sh(script: docker ps -qf name=[[DOCKER_IMAGE]], returnStdout: true).trim()
                        
                        sh 'docker exec ${containerId} python /app/test_app.py'
                    }
                }
            }
        }

        stage('Deploy to Production') {
            when {
                expression { return currentBuild.result == 'SUCCESS' }
            }
            steps {
                script {
                    sh docker-compose -f docker-compose.prod.yml up -d
                }
            }
        }

        stage('Teardown') {
            steps {
                script {

                    sh docker-compose down --volumes --remove-orphans
                }
            }
        }
    }

    post {
        always {
            cleanWs() 
    }
}
